# fly.toml app configuration file generated for dss-uploader on 2023-07-07T17:43:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dss-uploader"
primary_region = "cdg"

[env]
LOG_LEVEL = "debug"
MONGO_DB_NAME = "DSS"
MONGO_FILE_COLLECTION = "files"
PORT = "8080"
QUEUE_NAME = "DSS_QUEUE"
EXCHANGE_NAME = "fragments"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 2
